name: Build and Test
on:
  - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Mock build
        run: echo 'Build succeeded'
        shell: bash
    success: always
